### ISSUE TITLE
More github actions

### ISSUE THREAD

**Issue by chriscpritchard** [prisma-flowdiagram/PRISMA2020#18]
I think it would be really great if we could have github actions take some of the hard work out of version bumps / releases.

Functionality I'd like to see:

- [ ] on release tag automatically update zenodo release
- [ ] on release tag automatically deploy to shinyapps.io
- [ ] on release tag automatically submit to CRAN (I think this might be a bit tricky since they require email submissions, that said I do have my own mailserver so I could probably get that automated and CC all of us)

**Comment by nealhaddaway** [comment]
Zenodo and Shiny deployments sounds great to me! Can we set it to only deploy to CRAN on a major version increase? Just wondering if we'd be spamming if we push too frequently?
