### ISSUE TITLE
(Minor) automated comma missing

### ISSUE THREAD

**Issue by ajebach** [prisma-flowdiagram/PRISMA2020#38]
Only in Box two when values hit 4 digits, the comma is missing. See screenshot.

![image](https://user-images.githubusercontent.com/72057703/181425652-480e089c-419f-4adc-9331-280f48d84421.png)

**Comment by chriscpritchard** [comment]
Fairly sure that's my bad. I'll take a look hopefully soon and get it submitted. I can try and get the newest version submitted to CRAN to - it's been on my todo list!
