### ISSUE TITLE
Specific Databases not working

### ISSUE THREAD

**Issue by ajebach** [prisma-flowdiagram/PRISMA2020#45]
I can't seem to get Specific Databases or Specific Registers to appear when pulling from the csv template via the R package. 

I have tried setting the Databases (r6) and Registers (r8) rows to 'xxx', '', 'NA' in the 'n' column (H); and adding in some dummy numbers for the 3 default databases in the template.

I can get all other rows to edit as I wish, so I hope I am doing anything wrong, but any help/edits would be great.

If upload my csv onto the Shiny app it works, but doesn't when running on R.

**Data sheet:**
[data_prisma.csv](https://github.com/prisma-flowdiagram/PRISMA2020/files/10495619/data_prisma.csv)
**R screenshot:**
![Screenshot 2023-01-25 122857](https://user-images.githubusercontent.com/72057703/214467233-be8bb9c1-f59a-466d-9f8c-500040c97825.jpg)

**Comment by chriscpritchard** [comment]
I haven't updated the package on CRAN yet - for now you'll be able to get this feature by installing the github version.

**Comment by chriscpritchard** [comment]
Updated package on [CRAN](https://cran.r-project.org/package=PRISMA2020)
