### ISSUE TITLE
Resolution and sizing customisation

### ISSUE THREAD

**Issue by ajebach** [prisma-flowdiagram/PRISMA2020#46]
Much like ggsave or jpeg/tiff etc in R, it would be great if we could edit the resolution, width/height of the output plot in R. 

This would make it easier for authors to adhere to journal requirements for figures (e.g. dpi, filesize, dimensions).

**Comment by chriscpritchard** [comment]
Thank you for this, I'll look into it (unless someone wants to help) but I don't have much time at the moment!

**Comment by chriscpritchard** [comment]
Setting resolution of outputted file (with the exception of html and SVG as they're both vector types and generated differently internally) should be do-able if anyone is able to pick it up - rsvg takes a width and height argument.

I'll likely not have a chance to implement until the summer.
