### ISSUE TITLE
Error in PRISMA_flowdiagram() if reason for exclusion is 1

### ISSUE THREAD

**Issue by MiiroEm** [prisma-flowdiagram/PRISMA2020#52]
**An error comes when the a single reason of exclusion is supplied**
I'm trying to create a PRISMA flow diagram. The code works fine when the reasons for excluding a study is more than one but fails when I give a single reason. I first experienced it while using the **_R_** package but it also happens with the shinyapp.

**To Reproduce**
Steps to reproduce the behavior (using the example in the PRISMA2020 package documentation):
`library(PRISMA2020)`
`csvFile <- system.file("extdata", "PRISMA.csv", package = "PRISMA2020")`
`data <- read.csv(csvFile)`
`data[23, "n"] #three reasons are supplied in the template`
`data[23, "n"] <- "Reason1, xxx" #Replace with a single reason`
`data <- PRISMA_data(data)`
`PRISMA_flowdiagram(data,
                fontsize = 12,
                interactive = TRUE,
                previous = FALSE,
                other = TRUE)`

**Expected behavior**
A PRISMA flow diagram

**Screenshots**
error: Error in if (lines > min) { : the condition has length > 1
![image](https://github.com/prisma-flowdiagram/PRISMA2020/assets/116334187/408ca893-7ad9-4f49-98f2-acbab1413848)

**session info**
![image](https://github.com/prisma-flowdiagram/PRISMA2020/assets/116334187/b7d47168-c889-4092-9ed5-7404c7ef0661)
I'm using PRISMA2020  version 1.1.1  date 2023-02-09 CRAN (R 4.3.1)

I tried using the [shinyapp](https://estech.shinyapps.io/prisma_flowdiagram/)
Here's how to reproduce the error on the shinyapp
1. Go to the create flow diagram and click on reports excluded
![image](https://github.com/prisma-flowdiagram/PRISMA2020/assets/116334187/2d414983-fb0e-4487-b28c-a43d16bf8fb1)
2. Delete the 2 last reasons and leave only one
![image](https://github.com/prisma-flowdiagram/PRISMA2020/assets/116334187/d827bff9-6e54-492d-ab68-9c24dadb74c6)
3. An error comes: An error has occurred. Check your logs or contact the app author for clarification.
![image](https://github.com/prisma-flowdiagram/PRISMA2020/assets/116334187/90072cce-dbb5-4e62-a481-b6073977d525)

**More context**
Maintaining the ";" at the end of the reason supplied doesn't solve the issue.

Help will be appreciated. Thanks.

**Comment by LandauerTUM** [comment]
I have the same problem. Unfortunately, there is still no solution.

**Comment by chriscpritchard** [comment]
Hi,

It's on my list to try to resolve unfortunately I've been really busy with teaching this year so haven't had a chance to review. I'll try to get to it at some point soon as it's high on my priority list!

**Comment by chriscpritchard** [comment]
@MiiroEm @LandauerTUM Sorry how long this has taken to fix! Hopefully this should now be working on [the test site](https://prismaflow-test.shinyapps.io/PRISMA_flowdiagram/) and soon (once the workflow has completed) on [the main branch](https://estech.shinyapps.io/PRISMA_flowdiagram_latest/)

I'll look to publish a new release to [the main site](https://estech.shinyapps.io/prisma_flowdiagram/) once I've sorted some other outstanding issues.
