### ISSUE TITLE
NO ME DEJA ACCEDER A LA APP PARA CREAR DAGRAMA DE FLUJO PRISMA 2020

### ISSUE THREAD

**Issue by VeriSanchez** [prisma-flowdiagram/PRISMA2020#58]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by VeriSanchez** [comment]
NO PUEDO ACCEDER A LA APP DE DIAGRAMA DE FLUJO Y LO NECESITO URGENTE PARA HACER MI TRABAJO FIN DE CARRERA . GRACIAS

**Comment by befriendabacterium** [comment]
mira esto https://groups.google.com/g/shiny-discuss/c/cGbnVQbutLI?pli=1
