### ISSUE TITLE
Shiny App cannot be deployed. (PAGE NOT FOUND)

### ISSUE THREAD

**Issue by CoolShades** [prisma-flowdiagram/PRISMA2020#66]
There is a bug where the Shiny App is not deployed when following the steps described in the README.md

Step 1: Clone the Git Repo into a folder
Step 2: Build the image with `docker build . -t prisma-shiny:1` in the PRISMA2020 directory
Step 3: Deploy the app with `docker run -it --rm -p 3838:3838 prisma-shiny:1`
Step 4: Go to localhost:3838

Outcome:
![image](https://github.com/prisma-flowdiagram/PRISMA2020/assets/5731515/f737db22-e0a3-486f-90e5-da81211a8b71)

**Comment by chriscpritchard** [comment]
I don't use docker, so if there are any logs etc you can post (or send to me) that would be helpful

**Comment by chriscpritchard** [comment]
So I've just installed docker and taken a look, it's working fine for me - make sure you're going to http://localhost:3838/app rather than just http://localhost:3838 (http://localhost:3838 goes to the same page your screenshot shows).
